#include <iostream>
/*
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 
2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence 
whose values do not exceed four million, find the sum 
of the even-valued terms.
*/
int main() {

	int sum = 0;

	int i = 1;
	int j = 2;
	
	while(j < 4000000) {

		//First check to see if it's 
		//even and add it up, then increment
		if(j % 2 == 0) {
			sum += j;
		}

		//Increment
		int temp = j;
		j = j+i;
		i = temp;
	}

	std::cout << sum << "\n";
}